In [62]:
# Boltzmann Machines using pytorch

# Importing the libraries
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.optim as optim
import torch.utils.data
from torch.autograd import Variable


In [63]:
# Preparing the training set and the test set
training_set = pd.read_csv('ml-100k/u1.base', delimiter = '\t')
training_set = np.array(training_set, dtype = 'int')
test_set = pd.read_csv('ml-100k/u1.test', delimiter = '\t')
test_set = np.array(test_set, dtype = 'int')

In [64]:
print("Training set is:\n",training_set)
print('\n\n\n')
print("Test set is:\n",test_set)

Training set is:
 [[        1         2         3 876893171]
 [        1         3         4 878542960]
 [        1         4         3 876893119]
 ...
 [      943      1188         3 888640250]
 [      943      1228         3 888640275]
 [      943      1330         3 888692465]]




Test set is:
 [[        1        10         3 875693118]
 [        1        12         5 878542960]
 [        1        14         5 874965706]
 ...
 [      459       934         3 879563639]
 [      460        10         3 882912371]
 [      462       682         5 886365231]]


In [65]:
# Getting the number of users and movies
nb_users = int(max(max(training_set[:,0]), max(test_set[:,0])))
nb_movies = int(max(max(training_set[:,1]), max(test_set[:,1])))
print(nb_users)
print(nb_movies)

943
1682


In [66]:
# Converting the data into an array with users in rows and movies in columns
def convert(data):
    new_data = []
    for id_users in range(1, nb_users + 1):
        id_movies = data[:,1][data[:,0] == id_users]
        id_ratings = data[:,2][data[:,0] == id_users]
        ratings = np.zeros(nb_movies)
        ratings[id_movies - 1] = id_ratings
        new_data.append(list(ratings))
    return new_data

In [67]:
# Call convert 
training_set = convert(training_set)
test_set = convert(test_set)

In [68]:
print(training_set[0][:10])
print(test_set[0][:10])

[0.0, 3.0, 4.0, 3.0, 3.0, 0.0, 4.0, 1.0, 5.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0]


In [69]:
# Converting the data into Torch tensors
training_set = torch.FloatTensor(training_set)
test_set = torch.FloatTensor(test_set)


In [70]:
print('Training set:\n', training_set)
print('Test set:\n', test_set)

Training set:
 tensor([[0., 3., 4.,  ..., 0., 0., 0.],
        [4., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [5., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 5., 0.,  ..., 0., 0., 0.]])
Test set:
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [71]:
# Converting the ratings 1-5 into binary ratings 1 (Liked) or 0 (Not Liked)
training_set[training_set == 0] = -1
training_set[training_set == 1] = 0
training_set[training_set == 2] = 0
training_set[training_set >= 3] = 1
test_set[test_set == 0] = -1
test_set[test_set == 1] = 0
test_set[test_set == 2] = 0
test_set[test_set >= 3] = 1

In [72]:
# Creating the architecture of the Neural Network
class RBM():
    # Initialize Weights W of shape no. of visible nodes times no. of hidden nodes
    # a is the bais for hidden nodes
    # b is the bais for visible nodes
    def __init__(self, nv, nh):
        self.W = torch.randn(nh, nv)
        self.a = torch.randn(1, nh)
        self.b = torch.randn(1, nv)
    
    # sample_h function is used for calculating probability of each hidden nodes given the value of visible nodes
    # x is visible nodes, wx is weights of visible nodes obtained by multiplication of visble nodes and transpose of weights.
    # Use sigmoid function to get the probability of each hidden node  
    def sample_h(self, x):
        wx = torch.mm(x, self.W.t())
        activation = wx + self.a.expand_as(wx)
        p_h_given_v = torch.sigmoid(activation)
        return p_h_given_v, torch.bernoulli(p_h_given_v)
    
    # sample_v function is used for calculating probability of each visible node given the value of hidden nodes. Rest is similiar to the above function
    def sample_v(self, y):
        wy = torch.mm(y, self.W)
        activation = wy + self.b.expand_as(wy)
        p_v_given_h = torch.sigmoid(activation)
        return p_v_given_h, torch.bernoulli(p_v_given_h)
    
    # v0 = initial visible node, vk = visible node after k samples, ph0 = initial hidden nodes, phk = hidden node after k samples
    # follow the standard training algorithm of Boltzmann machines
    def train(self, v0, vk, ph0, phk):
        self.W += (torch.mm(v0.t(), ph0) - torch.mm(vk.t(), phk)).t()
        self.b += torch.sum((v0 - vk), 0)
        self.a += torch.sum((ph0 - phk), 0)
        
    def predict(self, x): # x: visible nodes
        _, h = self.sample_h(x)
        _, v = self.sample_v(h)
        return v

In [73]:
# Creating object of RBM class

nv = len(training_set[0])
nh = 100
batch_size = 100
rbm = RBM(nv, nh)

In [74]:
# Training the RBM
nb_epoch = 10
for epoch in range(1, nb_epoch + 1):
    train_loss = 0
    s = 0.
    for id_user in range(0, nb_users - batch_size, batch_size):
        vk = training_set[id_user:id_user+batch_size]
        v0 = training_set[id_user:id_user+batch_size]
        ph0,_ = rbm.sample_h(v0)
        for k in range(10):
            _,hk = rbm.sample_h(vk)
            _,vk = rbm.sample_v(hk)
            vk[v0<0] = v0[v0<0]
        phk,_ = rbm.sample_h(vk)
        rbm.train(v0, vk, ph0, phk)
        train_loss += torch.mean(torch.abs(v0[v0>=0] - vk[v0>=0]))
        s += 1.
    print('epoch: '+str(epoch)+' loss: '+str(train_loss/s))


epoch: 1 loss: tensor(0.3426)
epoch: 2 loss: tensor(0.2464)
epoch: 3 loss: tensor(0.2514)
epoch: 4 loss: tensor(0.2498)
epoch: 5 loss: tensor(0.2519)
epoch: 6 loss: tensor(0.2456)
epoch: 7 loss: tensor(0.2508)
epoch: 8 loss: tensor(0.2501)
epoch: 9 loss: tensor(0.2485)
epoch: 10 loss: tensor(0.2460)


In [75]:
# Testing the RBM
test_loss = 0
s = 0.
for id_user in range(nb_users):
    # Original visible nodes required for sample_h
    v = training_set[id_user:id_user+1]
    # Testing visible nodes
    vt = test_set[id_user:id_user+1]
    if len(vt[vt>=0]) > 0:
        _,h = rbm.sample_h(v)
        _,v = rbm.sample_v(h)
        test_loss += torch.mean(torch.abs(vt[vt>=0] - v[vt>=0]))
        s += 1.
print('test loss: '+str(test_loss/s))

test loss: tensor(0.2511)


In [76]:
# Call predict function to get results of 'User-1' from the test set. Similarly we can get predicted movies results for other users too.
user_id = 1
user_input = Variable(test_set[user_id -1]).unsqueeze(0)
op = rbm.predict(user_input)
op = op.data.numpy()
ip_op = np.vstack([user_input, op])

In [91]:
import pandas as pd
f = pd.DataFrame(ip_op.T, columns = ['Original Ratings', 'Predicted Ratings'])
print('Ignore predictions where original ratings are -1 because that resembles no original value present for that movie')
print("\nUser-1's likely predicted ratings for all 1682 movies:\n")
print("Displaying movies' ratings where origial ratings are not -1:")
f[f['Original Ratings']!= -1.0]


Ignore predictions where original ratings are -1 because that resembles no original value present for that movie

User-1's likely predicted ratings for all 1682 movies:

Displaying movies' ratings where origial ratings are not -1:


Original Ratings  Predicted Ratings
9                 1.0                1.0
11                1.0                1.0
13                1.0                1.0
16                1.0                1.0
19                1.0                0.0
..                ...                ...
263               0.0                1.0
264               1.0                1.0
265               0.0                0.0
266               1.0                0.0
271               1.0                1.0

[136 rows x 2 columns]